import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import { Inter } from "next/font/google";
import Header from "./components/header/Header";
import "./globals.css";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CookiesProvider>
      <html lang="en">
        <body className={`${inter.className} h-auto pt-0`}>
          <Header/>
          <div className="relative top-24 h-auto pt-0">
            {children}
          </div>
          <Footer/>
        </body>
      </html>
    </CookiesProvider>
  );
}
